export const LOCALIZE_CONST = {
   ABOUT_US: "ABOUT_US",
   ACCOUNT: "ACCOUNT",
   ACCOUNT_REGISTER: "ACCOUNT_REGISTER",
   APP_NAME: "APP_NAME",
   BACK: "BACK",
   CATEGORIES: "CATEGORIES",
   CHAPTER: "CHAPTER",
   CHAPTER_REGISTER: "CHAPTER_REGISTER",
   CONFIRM_PASSWORD: "CONFIRM_PASSWORD",
   CONTACT_US: "CONTACT_US",
   CONTENT: "CONTENT",
   COVER_IMAGE: "COVER_IMAGE",
   DESCRIPTION: "DESCRIPTION",
   EDITOR_CHOICES: "EDITOR_CHOICES",
   EDIT_PROFILE: "EDIT_PROFILE",
   EMAIL: "EMAIL",
   HOME: "HOME",
   IS_DONT_HAVE_ACC: "IS_DONT_HAVE_ACC",
   IS_HAVE_ACC: "IS_HAVE_ACC",
   LATEST_NOVELS: "LATEST_NOVELS",
   LOADING_POPULAR_NOVELS: "LOADING_POPULAR_NOVELS",
   LOGIN: "LOGIN",
   LOGIN_HERE: "LOGIN_HERE",
   LOGOUT: "LOGOUT",
   MY_BOOKS: "MY_BOOKS",
   MY_PROFILE: "MY_PROFILE",
   NAME: "NAME",
   NEXT: "NEXT",
   NO_BOOKMARK: "NO_BOOKMARK",
   NOVEL: "NOVEL",
   NOVEL_REGISTER: "NOVEL_REGISTER",
   NOVELS: "NOVELS",
   NO_BOOKS_FOUND: "NO_BOOKS_FOUND",
   ONGOING: "ONGOING",
   ORIGINAL_AUTHOR_NAME: "ORIGINAL_AUTHOR_NAME",
   ORIGINAL_NOVEL_NAME: "ORIGINAL_NOVEL_NAME",
   PASSWORD: "PASSWORD",
   PICK: "PICK",
   POPULAR_IN_THIS_MONTH: "POPULAR_IN_THIS_MONTH",
   POPULAR_IN_THIS_WEEK: "POPULAR_IN_THIS_WEEK",
   READ: "READ",
   READER_GUIDE: "READER_GUIDE",
   REGISTER: "REGISTER",
   REGISTER_HERE: "REGISTER_HERE",
   REMOVE: "REMOVE",
   SEARCH_PLACEHOLDER: "SEARCH_PLACEHOLDER",
   SIGN_IN: "SIGN_IN",
   TITLE: "TITLE",
   UPLOAD: "UPLOAD",
   UPLOAD_CHAPTER: "UPLOAD_CHAPTER",
   VOLUME: "VOLUME",
   VOLUME_TITLE: "VOLUME_TITLE"
}

export const LOCALIZE_CODE = {
   MYANMAR: "mm",
   ENGLISH: "en"
}

export const ROUTES = {
   ABOUT_US: "/about-us",
   CHAPTER_BY_ID: "/novels/:novel/chapters/:chapter",
   CONTACT_US: "/contact-us",
   GET_AUTHOR_INFO_NOVELS: "/author/:id",
   GET_BOOKMARK_COLLECTION: "/getBookMarkedCollection",
   GET_USER_INFO: "/me",
   HOME: "/",
   LOGOUT: "/logout",
   MY_BOOKS: "/my-books",
   MY_PROFILE: "/my-profile",
   NOVEL_BY_AUTHORS: "/novelsByAuthors",
   NOVEL_BY_ID: "/novels/:id",
   NOVELS: "/novels",
   RATE_NOVEL: "/novels/:id/rate",
   READER_GUIDE: "/guides",
   SEARCH: "/search",
   SIGN_IN: "/sign-in",
   TO_AUTHOR: "/author/:id",
   UPLOAD_CHAPTER: "/upload-chapters",
   UPDATE_CHAPTER: "/update-chapters/:novelId/:chapterId",
}

export const LINKS = [
   {
      icon: "SelectFace3d",
      title: LOCALIZE_CONST.READER_GUIDE,
      href: ROUTES.READER_GUIDE,
   },
];

export const FOOTER_LINKS = [
   {
      title: LOCALIZE_CONST.ABOUT_US,
      href: ROUTES.ABOUT_US,
   },
   {
      title: LOCALIZE_CONST.CONTACT_US,
      href: ROUTES.CONTACT_US,
   },
]

export const UPLOAD_MENU = {
   icon: "CloudUpload",
   title: LOCALIZE_CONST.UPLOAD_CHAPTER,
   href: ROUTES.UPLOAD_CHAPTER,
};

export const BOOKMARK_MENU = {
   icon: "MultiplePages",
   title: LOCALIZE_CONST.MY_BOOKS,
   href: ROUTES.MY_BOOKS,
}

export const DEFAULT_IMG_CHAR = "https://placehold.co/128x128/374151/FFFFFF?text=:char";